# 1.0.0.0 - 05 Feb 2022
# https://github.com/marketplace/actions/wiki-action
name: Update Wiki

on: 
  push:
    paths:
      - 'wiki/**'
      - 'docs/**'
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ineshbose/wiki-action@v1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WIKI_DIR: 'wiki'
          AUTO_SIDEBAR: true
